version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: hayroo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./server
    container_name: hayroo-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
    container_name: hayroo-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongodb_data: