apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: bilalasif8989/hayroo-backend:v2
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE
              value: mongodb://mongodb-service:27017/ecommerce

            - name: PORT
              value: "8000"